		location = /forum/config.php { deny all; }
		location = /forum/common.php { deny all; }
		location /forum/cache/ { deny all; }
		location /forum/config/ { deny all; }
		location /forum/files/ { deny all; }
		location /forum/images/avatars/upload/ { deny all; }
		location /forum/includes/ { deny all; }
		location /forum/store/ { deny all; }
